[package]
name = "dhtestingapp"
version = "0.1.0"
authors = ["Daniel Holland <danielholland414@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.10.0"
actix-web = "3"
serde = "1"
env_logger = "0.8.3"